### ISSUE TITLE
Improved land protection plugin

### ISSUE THREAD

**Issue by Aeviro** [Aeviro/KCMC#18]
I'm thinking about replacing Towny with a more advanced GUI based protection system. All Towny land claims will be imported to the new one if the decision to switch is made.

**Comment by codesidian** [comment]
People already struggle with Towny, could adding a more advanced system cause more confusion?

**Comment by Aeviro** [comment]
This one is much more user friendly. There is no use for commands and the GUI lists all the chunks that you have claimed. I don't think I'll be going along with the switch anyways.
